---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clinic.fullname" . }}-input-cm
  labels:
    app.kubernetes.io/name: {{ include "clinic.name" $ }}
    helm.sh/chart: {{ include "clinic.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
data:
{{ (.Files.Glob "conf/*").AsConfig | indent 2 }}