{{- if $.Values.server.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clinic.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "clinic.name" $ }}
    helm.sh/chart: {{ include "clinic.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: clinic-server
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  replicas: {{ $.Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clinic.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: clinic-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clinic.name" $ }}
        helm.sh/chart: {{ include "clinic.chart" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: clinic-server
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
        {{- with $.Values.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap_server.yaml") $ | sha256sum }}
        traffic.sidecar.istio.io/excludeOutboundPorts: "7233"
        {{- if $.Values.server.metrics.annotations.enabled }}
        prometheus.io/job: {{ $.Chart.Name }}-clinic-server
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        {{- end }}
        {{- with $.Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ include "clinic.serviceAccount" $ }}
      securityContext:
        fsGroup: 1101 #clinic.group
        runAsUser: 1101 #clinic.user
      containers:
        - name: {{ $.Chart.Name }}-server
          image: "{{ $.Values.server.image.repository }}:{{ $.Values.server.image.tag }}"
          imagePullPolicy: {{ $.Values.server.image.pullPolicy }}
          env:
            - name: INPUT_FILE
              value: {{ $.Values.server.config.inputFile }}
          ports:
            - name: http
              containerPort: {{ $.Values.server.service.port }}
              protocol: TCP
          volumeMounts:
            - name: input-config
              mountPath: /input
            {{- if $.Values.server.additionalVolumeMounts }}
            {{- toYaml $.Values.server.additionalVolumeMounts | nindent 12}}
            {{- end }}
          resources:
            {{- toYaml $.Values.server.resources | nindent 12 }}
        {{- if $.Values.server.sidecarContainers }}
        {{- toYaml $.Values.server.sidecarContainers | nindent 8 }}
        {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: input-config
          configMap:
            name: {{ include "clinic.fullname" . }}-input-cm
        {{- if $.Values.server.additionalVolumes }}
        {{- toYaml $.Values.server.additionalVolumes | nindent 8}}
        {{- end }}
      {{- with $.Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}