{{- if $.Values.server.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinic.fullname" . }}-svc
  labels:
    app.kubernetes.io/name: {{ include "clinic.name" . }}
    helm.sh/chart: {{ include "clinic.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: clinic-server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  {{- if .Values.server.service.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.server.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if hasKey .Values.server.service "nodePort" }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "clinic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: clinic-server
{{- end }}